开始训练...
训练集数据处理。。。。
=============
验证集数据处理。。。。。
=============
0
epoch: 0, batch_id: 0, loss is：0.9642
epoch: 0, batch_id: 10, loss is：0.7738
D:\Users\Admin\Python37\lib\site-packages\paddle\nn\layer\norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "D:/Users/Admin/PycharmProjects/PyCharm_Projects/Deep_learning/cat_dog/model_training02.py", line 116, in <module>
    train(model, EPOCH_NLM, opt)
  File "D:/Users/Admin/PycharmProjects/PyCharm_Projects/Deep_learning/cat_dog/model_training02.py", line 74, in train
    acc = fluid.layers.accuracy(pred, label)
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\fluid\layers\metric_op.py", line 88, in accuracy
    total)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds float, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/tensor_impl.h:33)
  [operator < accuracy > error]
开始训练...
训练集数据处理。。。。
=============
验证集数据处理。。。。。
=============
0
epoch: 0, batch_id: 0, loss is：0.6738
epoch: 0, batch_id: 10, loss is：0.2252
[validation] accuracy 0.3750, loss 0.9383
1
epoch: 1, batch_id: 0, loss is：0.1852
epoch: 1, batch_id: 10, loss is：0.0616
[validation] accuracy 0.3750, loss 0.9383
2
epoch: 2, batch_id: 0, loss is：0.0753
epoch: 2, batch_id: 10, loss is：0.0323
[validation] accuracy 0.3750, loss 0.9383
3
epoch: 3, batch_id: 0, loss is：0.0432
epoch: 3, batch_id: 10, loss is：0.0182
[validation] accuracy 0.3750, loss 0.9383
4
epoch: 4, batch_id: 0, loss is：0.0354
epoch: 4, batch_id: 10, loss is：0.0141
[validation] accuracy 0.3750, loss 0.9383
D:\Users\Admin\Python37\lib\site-packages\paddle\nn\layer\norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
